mod-name: NearFutureElectrical
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - NearFutureElectrical
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.0.2
    location: s3
  B9PartSwitch:
    version: 2.6.0
    location: s3
  CommunityResourcePack:
    version: 1.0.0
    location: s3
  DynamicBatteryStorage:
    tag: 1.4.1
    location: github
    repository: ChrisAdderley/DynamicBatteryStorage
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 558  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 220671  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
